# Documentation:
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            preset: win-msvc-release
          - os: ubuntu-24.04
            preset: linux-gcc-release
          - os: ubuntu-24.04
            preset: linux-clang-release

    steps:
    - uses: actions/checkout@v4

    - name: Set Env
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build/${{ matrix.preset }}" >> "$GITHUB_OUTPUT"

    - name: Install Ninja Linux
      if: runner.os == "Linux"
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build
    
    - name: Install Ninja Windows
      if: runner.os == "Windows"
      run: choco install ninja -y
    
    - name: Configure CMake
      working-directory: ${{ github.workspace }}
      run: |
        ls -la
        cmake --version
        cmake --preset ${{ matrix.preset }}

    - name: Build
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        ls -la
        ninja

    - name: Test Linux
      if: runner.os == "Linux"
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        ./action_cli

    - name: Test Windows
      if: runner.os == "Windows"
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        ./action_cli.exe
