# Documentation:
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: win-msvc-release
            os: windows-2022
          - preset: win-clang-release
            os: windows-2022
          - preset: linux-gcc-release
            os: ubuntu-24.04
          - preset: linux-clang-release
            os: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # required so cmake finds msvc compilers
    - uses: ilammy/msvc-dev-cmd@v1
    
    - uses: seanmiddleditch/gha-setup-ninja@v5

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with: 
        version: 6.7.2

    - name: Variables
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build/${{ matrix.preset }}" >> "$GITHUB_OUTPUT"
    
    - name: Configure CMake
      working-directory: ${{ github.workspace }}
      run: |
        cmake --version
        cmake --preset ${{ matrix.preset }}

    - name: Build
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        ninja -v
    
    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      env:
        QT_QPA_PLATFORM: offscreen
      # use wildcard * to capture .exe on windows
      run: |
        ./action_cli*
